### ISSUE TITLE
feat: 구매내역 페이지 제작 

### ISSUE THREAD

**Issue by bizbaeja** [GNDVMall/GNDV-front#12]
## Todo 추가 기능
- [ ] 공통 컴포넌트 배치하기 
- [ ] 구매한 내역을 가져오는 api 를 매핑하는 컴포넌트를 만들기 
- [ ] 판매내역에서도 사용할  수 있게  공통 컴포넌트로 만들기
